# Keras Basics

In [37]:
import numpy as np
from numpy import genfromtxt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.preprocessing import MinMaxScaler

from keras.models import Sequential
from keras.models import load_model
from keras.layers import Dense

In [2]:
data = genfromtxt("bank_note_data.txt", delimiter=",")

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
len(data)

1372

In [5]:
# Class
labels = data[:, 4]

In [6]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
# Features
features = data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

### Train Test Split

In [9]:
X = features
y = labels

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### Standardization

In [11]:
scaler_object = MinMaxScaler()

In [12]:
scaler_object.fit(X_train)

MinMaxScaler()

In [13]:
scaled_X_train = scaler_object.transform(X_train)

In [14]:
scaled_X_test = scaler_object.transform(X_test)

### Define Model

In [15]:
model = Sequential()

In [16]:
# Input Layer
model.add(Dense(4, input_dim=4, activation="relu"))

# Hidden Layer
model.add(Dense(8, activation="relu"))

# Output Layer
model.add(Dense(1, activation="sigmoid"))

In [21]:
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

### Fit Model on Train

In [22]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
29/29 - 1s - loss: 0.0620 - accuracy: 0.9717 - 551ms/epoch - 19ms/step
Epoch 2/50
29/29 - 0s - loss: 0.0602 - accuracy: 0.9771 - 28ms/epoch - 974us/step
Epoch 3/50
29/29 - 0s - loss: 0.0595 - accuracy: 0.9771 - 31ms/epoch - 1ms/step
Epoch 4/50
29/29 - 0s - loss: 0.0598 - accuracy: 0.9750 - 28ms/epoch - 977us/step
Epoch 5/50
29/29 - 0s - loss: 0.0577 - accuracy: 0.9782 - 32ms/epoch - 1ms/step
Epoch 6/50
29/29 - 0s - loss: 0.0573 - accuracy: 0.9750 - 30ms/epoch - 1ms/step
Epoch 7/50
29/29 - 0s - loss: 0.0560 - accuracy: 0.9761 - 28ms/epoch - 975us/step
Epoch 8/50
29/29 - 0s - loss: 0.0564 - accuracy: 0.9761 - 31ms/epoch - 1ms/step
Epoch 9/50
29/29 - 0s - loss: 0.0552 - accuracy: 0.9804 - 33ms/epoch - 1ms/step
Epoch 10/50
29/29 - 0s - loss: 0.0541 - accuracy: 0.9793 - 36ms/epoch - 1ms/step
Epoch 11/50
29/29 - 0s - loss: 0.0537 - accuracy: 0.9782 - 32ms/epoch - 1ms/step
Epoch 12/50
29/29 - 0s - loss: 0.0536 - accuracy: 0.9804 - 38ms/epoch - 1ms/step
Epoch 13/50
29/29 - 0s - loss

### Test Prediction

In [27]:
# np.where(y_pred > threshold, 1,0)

In [28]:
model.metrics_names

['loss', 'accuracy']

### Evaluation

In [29]:
model.metrics_names

['loss', 'accuracy']

In [32]:
predictions = model.predict(scaled_X_test)

15/15 [==============================] - 0s 1ms/step


In [33]:
predictions = np.where(predictions > 0.5, 1, 0)

In [34]:
confusion_matrix(y_test, predictions)

array([[253,   4],
       [  2, 194]])

In [35]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.99      0.98      0.99       257
         1.0       0.98      0.99      0.98       196

    accuracy                           0.99       453
   macro avg       0.99      0.99      0.99       453
weighted avg       0.99      0.99      0.99       453



### Save Model

In [36]:
model.save("model.h5")

### Load Model

In [38]:
model = load_model("model.h5")