# Keras Basics

In [1]:
import numpy as np
from numpy import genfromtxt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

from keras.models import Sequential
from keras.layers import Dense

In [2]:
data = genfromtxt("bank_note_data.txt", delimiter=",")

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
len(data)

1372

In [5]:
# Class
labels = data[:, 4]

In [6]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
# Features
features = data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

### Train Test Split

In [9]:
X = features
y = labels

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### Standardization

In [11]:
scaler_object = MinMaxScaler()

In [12]:
scaler_object.fit(X_train)

MinMaxScaler()

In [13]:
scaled_X_train = scaler_object.transform(X_train)

In [14]:
scaled_X_test = scaler_object.transform(X_test)

### Define Model

In [15]:
model = Sequential()

In [16]:
# Input Layer
model.add(Dense(4, input_dim=4, activation="relu"))

# Hidden Layer
model.add(Dense(8, activation="relu"))

# Output Layer
model.add(Dense(1, activation="sigmoid"))

In [17]:
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])