# Numpy Arrays

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist, np.uint8)

array([1, 2, 3], dtype=uint8)

In [7]:
myarray = np.array(mylist, np.uint8)

In [8]:
myarray

array([1, 2, 3], dtype=uint8)

In [9]:
type(myarray)

numpy.ndarray

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [32]:
zeros = np.zeros(shape=(5,3))

In [14]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.random.seed(101)

In [18]:
arr = np.random.randint(0, 100, 10)

In [19]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [20]:
arr2 = np.random.randint(0, 100, 10)

In [21]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [22]:
np.max(arr2)

93

In [23]:
np.min(arr2)

4

In [25]:
arr2.argmax()

8

In [26]:
arr2.max()

93

In [27]:
arr2.min()

4

In [28]:
arr2.mean()

47.3

In [29]:
arr.mean()

60.8

In [30]:
 arr.shape

(10,)

In [31]:
arr2.shape

(10,)

In [33]:
zeros.shape

(5, 3)

In [34]:
zeros.min()

0.0

In [35]:
zeros.max()

0.0

In [36]:
zeros.argmax()

0

In [37]:
zeros.argmin()

0

In [38]:
marray = np.random.random(size=(5,4))

In [39]:
marray

array([[0.1818924 , 0.78560176, 0.96548322, 0.23235366],
       [0.08356143, 0.60354842, 0.72899276, 0.27623883],
       [0.68530633, 0.51786747, 0.04848454, 0.13786924],
       [0.18696743, 0.9943179 , 0.5206654 , 0.57878954],
       [0.73481906, 0.54196177, 0.91315356, 0.80792015]])

In [40]:
marray.max()

0.994317901154097

In [41]:
marray.argmax()

13

In [42]:
marray.shape

(5, 4)

In [45]:
resahpe_array = marray.reshape((10,-1))

In [46]:
resahpe_array

array([[0.1818924 , 0.78560176],
       [0.96548322, 0.23235366],
       [0.08356143, 0.60354842],
       [0.72899276, 0.27623883],
       [0.68530633, 0.51786747],
       [0.04848454, 0.13786924],
       [0.18696743, 0.9943179 ],
       [0.5206654 , 0.57878954],
       [0.73481906, 0.54196177],
       [0.91315356, 0.80792015]])

In [47]:
arr.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [50]:
mat = np.arange(0,100).reshape(10,10)

In [51]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
mat.shape

(10, 10)

In [53]:
mat[5,3]

53

In [54]:
mat[5][3]

53

In [55]:
mat[3:5, 5:9]

array([[35, 36, 37, 38],
       [45, 46, 47, 48]])

In [56]:
row = 0
column = 1

In [57]:
print(mat[row, column])

1


In [58]:
# grab 46
row = 4
column = 6
print(mat[row, column])

46


In [60]:
print(mat[row][column])

46


In [61]:
# all row
mat[3,]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [63]:
mat[3][:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [64]:
mat[3, :]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [66]:
 mat[0, :].shape

(10,)

In [67]:
mat[0, :].reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [68]:
mat[0, :].reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [69]:
mat[0:4, 3:8] = 22

In [70]:
mat

array([[ 0,  1,  2, 22, 22, 22, 22, 22,  8,  9],
       [10, 11, 12, 22, 22, 22, 22, 22, 18, 19],
       [20, 21, 22, 22, 22, 22, 22, 22, 28, 29],
       [30, 31, 32, 22, 22, 22, 22, 22, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [71]:
my_copy  = mat.copy()

In [72]:
my_copy[4:8, 3: 9] = 500

In [73]:
my_copy

array([[  0,   1,   2,  22,  22,  22,  22,  22,   8,   9],
       [ 10,  11,  12,  22,  22,  22,  22,  22,  18,  19],
       [ 20,  21,  22,  22,  22,  22,  22,  22,  28,  29],
       [ 30,  31,  32,  22,  22,  22,  22,  22,  38,  39],
       [ 40,  41,  42, 500, 500, 500, 500, 500, 500,  49],
       [ 50,  51,  52, 500, 500, 500, 500, 500, 500,  59],
       [ 60,  61,  62, 500, 500, 500, 500, 500, 500,  69],
       [ 70,  71,  72, 500, 500, 500, 500, 500, 500,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [74]:
mat

array([[ 0,  1,  2, 22, 22, 22, 22, 22,  8,  9],
       [10, 11, 12, 22, 22, 22, 22, 22, 18, 19],
       [20, 21, 22, 22, 22, 22, 22, 22, 28, 29],
       [30, 31, 32, 22, 22, 22, 22, 22, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])